Repository clusterpedia-io/clusterpedia, pull requests merged in 2022-11, with the labels that each got.

#437 update api readme.md
  staging/src/github.com/clusterpedia-io/api/README.md
Labels: kind/documentation, size/XS

#439 Bump github.com/stretchr/testify from 1.8.0 to 1.8.1
  go.mod
  go.sum
  vendor/modules.txt
Labels: kind/cleanup, lgtm, size/XS

#427 Bump gorm.io/driver/mysql from 1.3.6 to 1.4.3
  go.mod
  go.sum
  vendor/gorm.io/driver/mysql/migrator.go
  vendor/gorm.io/driver/mysql/mysql.go
  vendor/modules.txt
Labels: kind/cleanup, kind/dependencies, size/XS

#339 Replace `fake-k8s.sh` with `kwokctl` in e2e-test
  test/cases/workable.test.sh
  test/helper.sh
Labels: kind/feature, lgtm, size/M

#438 Bump gorm.io/driver/postgres from 1.3.10 to 1.4.5
  go.mod
  go.sum
  vendor/gorm.io/driver/postgres/migrator.go
  vendor/gorm.io/driver/postgres/postgres.go
  vendor/gorm.io/gorm/README.md
  vendor/gorm.io/gorm/callbacks/associations.go
  vendor/gorm.io/gorm/callbacks/query.go
  vendor/gorm.io/gorm/chainable_api.go
  vendor/gorm.io/gorm/migrator/migrator.go
  vendor/gorm.io/gorm/prepare_stmt.go
  vendor/gorm.io/gorm/scan.go
  vendor/gorm.io/gorm/schema/serializer.go
  vendor/gorm.io/gorm/statement.go
  vendor/gorm.io/gorm/utils/utils.go
  vendor/modules.txt
Labels: kind/cleanup, lgtm, size/XS

#421 docs: add clusterimportpolicy example for kubevela #243
  deploy/clusterimportpolicy/kubevela.yaml
Labels: kind/documentation, lgtm, size/M

#440 optimize cluster monitor logic
  pkg/synchromanager/clustersynchro/cluster_monitor.go
Labels: lgtm, size/XS

#449 Bump sigs.k8s.io/controller-runtime from 0.13.0 to 0.13.1
  go.mod
  go.sum
  vendor/modules.txt
Labels: kind/cleanup, lgtm, kind/dependencies, size/XS

#447 rename *CustomResource function to *Unstructured
  pkg/kubeapiserver/restmanager.go
  pkg/kubeapiserver/storageconfig/storageconfig_factory.go
Labels: kind/cleanup, size/S

#450 move resourcescheme and storageconfig to pkg
  pkg/apiserver/registry/clusterpedia/collectionresources/rest.go
  pkg/kubeapiserver/restmanager.go
  pkg/scheme/import_known_versions.go
  pkg/scheme/scheme.go
  pkg/scheme/unstructured/scheme.go
  pkg/storage/internalstorage/collectionresource.go
  pkg/storage/memorystorage/watchcache/watch_cache.go
  pkg/storageconfig/storageconfig_factory.go
  pkg/synchromanager/clustersynchro/cluster_synchro.go
  pkg/synchromanager/clustersynchro/crd_controller.go
  pkg/synchromanager/clustersynchro/resource_negotiator.go
Labels: kind/cleanup, size/L

#451 storage: add GetSupportedRequestVerbs
  pkg/kubeapiserver/restmanager.go
  pkg/storage/internalstorage/storage.go
  pkg/storage/memorystorage/memory_storage.go
  pkg/storage/storage.go
Labels: kind/feature, lgtm, size/S

#445 storage: change the Watch method to use *internal.ListOptions
  pkg/kubeapiserver/resourcerest/storage.go
  pkg/storage/internalstorage/resource_storage.go
  pkg/storage/memorystorage/memory_resource_storage.go
  pkg/storage/storage.go
Labels: kind/feature, size/M

#436 support for using `go plugin` to register storage layer plugins
  .dockerignore
  .github/workflows/ci.yml
  .github/workflows/push-images.yml
  Dockerfile
  Makefile
  builder.dockerfile
  builder.dockerfile.dockerignore
  cmd/apiserver/app/apiserver.go
  cmd/binding-apiserver/app/binding_apiserver.go
  cmd/clustersynchro-manager/app/synchro.go
  hack/builder-nocgo.sh
  hack/builder.sh
  ldflags.sh
  pkg/storage/plugin.go
  test/helper.sh
Labels: kind/feature, size/L

#457 Bump gorm.io/driver/mysql from 1.4.3 to 1.4.4
  go.mod
  go.sum
  vendor/gorm.io/driver/mysql/migrator.go
  vendor/gorm.io/driver/mysql/mysql.go
  vendor/modules.txt
Labels: kind/cleanup, kind/dependencies, size/XS

#456 The dynamic discovery manager starts and stops based on cluster status
  pkg/discovery/controller/apiservice.go
  pkg/discovery/controller/crd.go
  pkg/discovery/discovery_cache.go
  pkg/discovery/dynamic_discovery.go
  pkg/discovery/server_version.go
  pkg/synchromanager/clustersynchro/apiservice_controller.go
  pkg/synchromanager/clustersynchro/cluster_monitor.go
  pkg/synchromanager/clustersynchro/cluster_synchro.go
  pkg/synchromanager/clustersynchro/crd_controller.go
  pkg/synchromanager/clustersynchro/discovery/dynamic_discovery_manager.go
  pkg/synchromanager/clustersynchro/resource_negotiator.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1/interface.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1beta1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1beta1/interface.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1/expansion_generated.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1beta1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1beta1/expansion_generated.go
  vendor/modules.txt
Labels: kind/bug, size/XXL

#459 use standalone tcp for health checker
  pkg/synchromanager/clustersynchro/cluster_monitor.go
  pkg/synchromanager/clustersynchro/cluster_synchro.go
  pkg/synchromanager/features/features.go
Labels: kind/feature, size/M

#461 internalstorage: add recoverable err
  pkg/storage/internalstorage/errors.go
Labels: kind/bug, lgtm, cherry-pick/0.5.x, size/S

#463 [release/0.5] internalstorage: add recoverable err
  pkg/storage/internalstorage/errors.go
Labels: kind/bug, size/S

#444 sync api by pipeline
  .github/workflows/sync-api.yml
  hack/sync-api.sh
Labels: kind/feature, size/L
