Repository clusterpedia-io/clusterpedia, pull requests merged in 2022-08, with the labels that each got.

#287 fix set dependent resources of the pediacluster lifecycle
  pkg/controller/pediaclusterlifecycle/pediaclusterlifecycle_controller.go
Labels: kind/bug

#290 update image tags to v0.4.1
  charts/Chart.yaml
  charts/values.yaml
  deploy/clusterpedia_apiserver_deployment.yaml
  deploy/clusterpedia_clustersynchro_manager_deployment.yaml
  deploy/clusterpedia_controller_manager_deployment.yaml
Labels: kind/cleanup

#288 add clusterimportpolicy yaml for cluster api
  deploy/clusterimportpolicy/cluster_api.yaml
Labels: kind/feature

#300 Fix the permission of bot and merge jobs into one
  .github/workflows/bot.yml
Labels: kind/bug

#307 Mv ioutil.ReadFile to os.ReadFile for fixing ci error
  pkg/storage/internalstorage/config.go
Labels: kind/bug, kind/cleanup

#305 Complete Helm README.md
  charts/README.md
Labels: kind/documentation

#316 Support `/retest` on ci bot
  .github/workflows/bot.yml
Labels: kind/feature

#310 Friendly printing pediaclusterlifecycle and clusterimportlifecycle
  charts/_crds/policy.clusterpedia.io_clusterimportpolicies.yaml
  charts/_crds/policy.clusterpedia.io_pediaclusterlifecycles.yaml
  staging/src/github.com/clusterpedia-io/api/policy/v1alpha1/types.go
Labels: kind/feature

#319 add source.selectorTemplate field for ClusterImportPolicy
  charts/clusterpedia/_crds/policy.clusterpedia.io_clusterimportpolicies.yaml
  examples/clusterimportpolicy.yaml
  pkg/controller/clusterimportpolicy/clusterimportpolicy_controller.go
  staging/src/github.com/clusterpedia-io/api/policy/v1alpha1/types.go
Labels: kind/feature

#320 e2e test failed and exit
  test/cases/workable.test.sh
  test/environments/default.env.sh
  test/environments/multiple.env.sh
  test/helper.sh
  test/test.sh
Labels: kind/cleanup, lgtm

#321 Update Helm Chart Readme
  charts/clusterpedia/README.md
Labels: kind/documentation

#317 Reduce the waiting time for ready in e2e
  test/cases/workable.test.sh
Labels: kind/cleanup

#325 Add gci to clusterpedia
  .golangci.yml
  cmd/controller-manager/app/controllermanager.go
Labels: kind/cleanup, lgtm

#327 add chart lint workflow
  .github/workflows/lint-chart.yaml
  charts/clusterpedia/Chart.lock
  charts/clusterpedia/Chart.yaml
  charts/clusterpedia/values.yaml
Labels: kind/feature, lgtm

#328 Add apiserver to status for display
  charts/clusterpedia/_crds/cluster.clusterpedia.io_pediaclusters.yaml
  pkg/synchromanager/clustersynchro_manager.go
  staging/src/github.com/clusterpedia-io/api/cluster/v1alpha2/types.go
Labels: kind/feature, lgtm
