Repository clusterpedia-io/clusterpedia, pull requests merged in 2022-09, with the labels that each got.

#335 sync apiregistration resources
  pkg/synchromanager/clustersynchro/apiservice_controller.go
Labels: kind/bug, lgtm

#338 use the clusterpedia-bot token in ci bot
  .github/workflows/bot.yml
Labels: kind/cleanup

#324 add clusterimportpolicy yaml for vcluster
  deploy/clusterimportpolicy/vcluster.yaml
Labels: kind/feature

#336 retry failed resource sync due to storage component exceptions
  pkg/storage/internalstorage/errors.go
  pkg/storage/storage.go
  pkg/synchromanager/clustersynchro/cluster_synchro.go
  pkg/synchromanager/clustersynchro/queue/pressurequeue.go
  pkg/synchromanager/clustersynchro/queue/queue.go
  pkg/synchromanager/clustersynchro/resource_synchro.go
Labels: kind/feature

#343 internalstorage: update default conn pool
  pkg/storage/internalstorage/config.go
Labels: kind/cleanup

#344 Update Charts Index
  charts/index.yaml
Labels: lgtm

#346 fix:The log config param level in helm chart is wrong
  charts/clusterpedia/templates/internalstorage-configmap.yaml
  charts/clusterpedia/values.yaml
Labels: kind/bug, lgtm

#332 add conn poll config
  charts/clusterpedia/Chart.yaml
  charts/clusterpedia/templates/internalstorage-configmap.yaml
  charts/clusterpedia/values.yaml
Labels: kind/feature, lgtm

#349 update image tags to 0.5.0 and update charts index.yaml
  charts/clusterpedia/Chart.yaml
  charts/clusterpedia/values.yaml
  charts/index.yaml
  deploy/clusterpedia_apiserver_deployment.yaml
  deploy/clusterpedia_clustersynchro_manager_deployment.yaml
  deploy/clusterpedia_controller_manager_deployment.yaml
Labels: kind/cleanup

#104 Create dependabot.yml
  .github/dependabot.yml
Labels: do-not-merge/hold, lgtm

#351 change kubernetes deps to k8s.io/kubernetes
  Makefile
  go.mod
  go.sum
  vendor/k8s.io/apimachinery/pkg/util/net/interface.go
  vendor/k8s.io/apiserver/pkg/server/config.go
  vendor/k8s.io/apiserver/pkg/server/options/deprecated_insecure_serving.go
  vendor/k8s.io/apiserver/pkg/server/options/serving.go
  vendor/k8s.io/apiserver/pkg/server/options/serving_with_loopback.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/store.go
  vendor/k8s.io/client-go/pkg/version/.gitattributes
  vendor/k8s.io/client-go/pkg/version/base.go
  vendor/k8s.io/component-base/version/.gitattributes
  vendor/k8s.io/component-base/version/base.go
  vendor/modules.txt
Labels: kind/cleanup

#363 Bumps sigs.k8s.io/controller-tools from 0.9.0 to 0.9.2
  charts/clusterpedia/_crds/cluster.clusterpedia.io_clustersyncresources.yaml
  charts/clusterpedia/_crds/cluster.clusterpedia.io_pediaclusters.yaml
  charts/clusterpedia/_crds/policy.clusterpedia.io_clusterimportpolicies.yaml
  charts/clusterpedia/_crds/policy.clusterpedia.io_pediaclusterlifecycles.yaml
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-tools/pkg/crd/flatten.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/gen.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/topology.go
  vendor/sigs.k8s.io/controller-tools/pkg/loader/loader.go
  vendor/sigs.k8s.io/controller-tools/pkg/schemapatcher/gen.go
Labels: kind/cleanup, lgtm, dependencies

#367 Bump golangci lint to v1.49.0
  .github/workflows/ci.yml
  Makefile
Labels: lgtm

#347 resolve Cluster Healthy Condition Message isn't empty
  pkg/synchromanager/clustersynchro/cluster_monitor.go
Labels: lgtm

#373 Mark pediacluster status.Version as optional field.#333
  staging/src/github.com/clusterpedia-io/api/cluster/v1alpha2/types.go
Labels: lgtm

#372 Support Create Database to External Storage
  charts/clusterpedia/templates/_helpers.tpl
  charts/clusterpedia/templates/apiserver-deployment.yaml
  charts/clusterpedia/templates/clustersynchro-manager-deployment.yaml
  charts/clusterpedia/values.yaml
Labels: lgtm

#345 Add memory storage for supporting ListAndWatch
  Makefile
  cmd/apiserver/app/options/options.go
  cmd/binding-apiserver/app/binding_apiserver.go
  cmd/binding-apiserver/main.go
  deploy/binding-apiserver/clusterpedia_binding_apiserver_apiservice.yaml
  deploy/binding-apiserver/clusterpedia_binding_apiserver_deployment.yaml
  deploy/binding-apiserver/clusterpedia_binding_apiserver_rbac.yaml
  pkg/apiserver/apiserver.go
  pkg/apiserver/registry/clusterpedia/collectionresources/rest.go
  pkg/kubeapiserver/apiserver.go
  pkg/kubeapiserver/resource_handler.go
  pkg/kubeapiserver/resourcerest/storage.go
  pkg/kubeapiserver/restmanager.go
  pkg/kubeapiserver/storageconfig/storageconfig_factory.go
  pkg/storage/internalstorage/register.go
  pkg/storage/internalstorage/resource_storage.go
  pkg/storage/internalstorage/storage.go
  pkg/storage/memorystorage/memory_resource_storage.go
  pkg/storage/memorystorage/memory_storage.go
  pkg/storage/memorystorage/register.go
  pkg/storage/memorystorage/watchcache/cache_watcher.go
  pkg/storage/memorystorage/watchcache/cluster_resource_version.go
  pkg/storage/memorystorage/watchcache/watch_cache.go
  pkg/storage/options/options.go
  pkg/storage/storage.go
  pkg/synchromanager/clustersynchro/cluster_synchro.go
  pkg/synchromanager/clustersynchro/resource_negotiator.go
  pkg/synchromanager/clustersynchro_manager.go
  pkg/utils/watch/watchevent.go
Labels: lgtm

#376 fix push images error
  Makefile
Labels: kind/bug, lgtm

#377 Bump gorm.io/driver/postgres from 1.3.9 to 1.3.10
  go.mod
  go.sum
  vendor/github.com/jackc/pgconn/CHANGELOG.md
  vendor/github.com/jackc/pgconn/config.go
  vendor/github.com/jackc/pgconn/defaults.go
  vendor/github.com/jackc/pgconn/errors.go
  vendor/github.com/jackc/pgconn/krb5.go
  vendor/github.com/jackc/pgconn/pgconn.go
  vendor/github.com/jackc/pgproto3/v2/backend.go
  vendor/github.com/jackc/pgproto3/v2/frontend.go
  vendor/github.com/jackc/pgtype/CHANGELOG.md
  vendor/github.com/jackc/pgtype/array_type.go
  vendor/github.com/jackc/pgtype/date.go
  vendor/github.com/jackc/pgtype/enum_type.go
  vendor/github.com/jackc/pgtype/hstore.go
  vendor/github.com/jackc/pgtype/inet.go
  vendor/github.com/jackc/pgtype/interval.go
  vendor/github.com/jackc/pgtype/json_array.go
  vendor/github.com/jackc/pgtype/numeric.go
  vendor/github.com/jackc/pgtype/pgtype.go
  vendor/github.com/jackc/pgtype/timestamp.go
  vendor/github.com/jackc/pgtype/timestamptz.go
  vendor/github.com/jackc/pgtype/typed_array_gen.sh
  vendor/github.com/jackc/pgtype/uuid.go
  vendor/github.com/jackc/pgx/v4/CHANGELOG.md
  vendor/github.com/jackc/pgx/v4/README.md
  vendor/github.com/jackc/pgx/v4/conn.go
  vendor/github.com/jackc/pgx/v4/copy_from.go
  vendor/github.com/jackc/pgx/v4/large_objects.go
  vendor/github.com/jackc/pgx/v4/logger.go
  vendor/github.com/jackc/pgx/v4/rows.go
  vendor/golang.org/x/crypto/AUTHORS
  vendor/golang.org/x/crypto/CONTRIBUTORS
  vendor/golang.org/x/crypto/cryptobyte/builder.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_generic.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_s390x.go
  vendor/golang.org/x/crypto/pbkdf2/pbkdf2.go
  vendor/golang.org/x/crypto/scrypt/scrypt.go
  vendor/gorm.io/driver/postgres/migrator.go
  vendor/modules.txt
Labels: kind/cleanup, kind/dependencies

#378 ci add setupgo action
  .github/workflows/ci.yml
Labels: lgtm

#382 update binding-apiserver image tags to latest
  cmd/binding-apiserver/app/binding_apiserver.go
  deploy/binding-apiserver/clusterpedia_binding_apiserver_deployment.yaml
Labels: lgtm

#350 support order by raw sql
  pkg/storage/internalstorage/util.go
  pkg/storage/internalstorage/util_test.go
Labels: lgtm

#390 Bump sigs.k8s.io/controller-runtime from 0.12.1 to 0.13.0.
  go.mod
  go.sum
  vendor/github.com/evanphx/json-patch/v5/LICENSE
  vendor/github.com/evanphx/json-patch/v5/errors.go
  vendor/github.com/evanphx/json-patch/v5/merge.go
  vendor/github.com/evanphx/json-patch/v5/patch.go
  vendor/github.com/fsnotify/fsnotify/CHANGELOG.md
  vendor/github.com/fsnotify/fsnotify/CONTRIBUTING.md
  vendor/github.com/fsnotify/fsnotify/README.md
  vendor/github.com/fsnotify/fsnotify/fsnotify_unsupported.go
  vendor/github.com/fsnotify/fsnotify/inotify.go
  vendor/github.com/fsnotify/fsnotify/inotify_poller.go
  vendor/github.com/fsnotify/fsnotify/kqueue.go
  vendor/github.com/fsnotify/fsnotify/windows.go
  vendor/github.com/prometheus/client_golang/prometheus/go_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/go_collector_go116.go
  vendor/github.com/prometheus/client_golang/prometheus/go_collector_latest.go
  vendor/github.com/prometheus/client_golang/prometheus/internal/go_runtime_metrics.go
  vendor/go.uber.org/zap/.readme.tmpl
  vendor/go.uber.org/zap/CHANGELOG.md
  vendor/go.uber.org/zap/README.md
  vendor/go.uber.org/zap/global.go
  vendor/go.uber.org/zap/global_prego112.go
  vendor/go.uber.org/zap/level.go
  vendor/go.uber.org/zap/logger.go
  vendor/go.uber.org/zap/stacktrace.go
  vendor/go.uber.org/zap/zapcore/clock.go
  vendor/go.uber.org/zap/zapcore/console_encoder.go
  vendor/go.uber.org/zap/zapcore/encoder.go
  vendor/go.uber.org/zap/zapcore/json_encoder.go
  vendor/go.uber.org/zap/zapcore/level.go
  vendor/go.uber.org/zap/zapcore/reflected_encoder.go
  vendor/go.uber.org/zap/zapcore/sampler.go
  vendor/golang.org/x/time/rate/rate.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/dynamicrestmapper.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/dryrun.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/interfaces.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/metadata_client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/namespaced_client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/options.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/patch.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/split.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/typed_client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/unstructured_client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/log/deleg.go
  vendor/sigs.k8s.io/controller-runtime/pkg/log/log.go
Labels: kind/cleanup, lgtm, kind/dependencies

#387 add GOVERNANCE.md and OWNERS
  GOVERNANCE.md
  OWNERS
  charts/OWNERS
  cmd/apiserver/OWNERS
  cmd/binding-apiserver/OWNERS
  cmd/clustersynchro-manager/OWNERS
  cmd/controller-manager/OWNERS
  deploy/OWNERS
  pkg/apiserver/OWNERS
  pkg/controller/OWNERS
  pkg/kubeapiserver/OWNERS
  pkg/storage/OWNERS
  pkg/storage/internalstorage/OWNERS
  pkg/synchromanager/OWNERS
  test/OWNERS
Labels: lgtm

#391 Bump gorm.io/gorm from 1.23.8 to 1.23.10
  go.mod
  go.sum
  vendor/gorm.io/gorm/.gitignore
  vendor/gorm.io/gorm/association.go
  vendor/gorm.io/gorm/callbacks/associations.go
  vendor/gorm.io/gorm/callbacks/update.go
  vendor/gorm.io/gorm/finisher_api.go
  vendor/gorm.io/gorm/gorm.go
  vendor/gorm.io/gorm/logger/logger.go
  vendor/gorm.io/gorm/logger/sql.go
  vendor/gorm.io/gorm/migrator.go
  vendor/gorm.io/gorm/migrator/migrator.go
  vendor/gorm.io/gorm/scan.go
  vendor/gorm.io/gorm/schema/field.go
  vendor/gorm.io/gorm/schema/relationship.go
  vendor/gorm.io/gorm/schema/schema.go
  vendor/gorm.io/gorm/schema/serializer.go
  vendor/gorm.io/gorm/statement.go
  vendor/modules.txt
Labels: kind/cleanup, kind/dependencies

#399 Bump sigs.k8s.io/controller-tools from 0.9.2 to 0.10.0
  charts/clusterpedia/_crds/cluster.clusterpedia.io_clustersyncresources.yaml
  charts/clusterpedia/_crds/cluster.clusterpedia.io_pediaclusters.yaml
  charts/clusterpedia/_crds/policy.clusterpedia.io_clusterimportpolicies.yaml
  charts/clusterpedia/_crds/policy.clusterpedia.io_pediaclusterlifecycles.yaml
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-tools/cmd/controller-gen/main.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/doc.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/flatten.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/known_types.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/doc.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/topology.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/spec.go
  vendor/sigs.k8s.io/controller-tools/pkg/genall/doc.go
  vendor/sigs.k8s.io/controller-tools/pkg/genall/help/pretty/doc.go
  vendor/sigs.k8s.io/controller-tools/pkg/genall/options.go
  vendor/sigs.k8s.io/controller-tools/pkg/genall/zz_generated.markerhelp.go
  vendor/sigs.k8s.io/controller-tools/pkg/loader/doc.go
  vendor/sigs.k8s.io/controller-tools/pkg/loader/loader.go
  vendor/sigs.k8s.io/controller-tools/pkg/markers/collect.go
  vendor/sigs.k8s.io/controller-tools/pkg/markers/doc.go
  vendor/sigs.k8s.io/controller-tools/pkg/markers/reg.go
  vendor/sigs.k8s.io/controller-tools/pkg/markers/zip.go
  vendor/sigs.k8s.io/controller-tools/pkg/rbac/parser.go
  vendor/sigs.k8s.io/controller-tools/pkg/schemapatcher/gen.go
  vendor/sigs.k8s.io/controller-tools/pkg/version/version.go
  vendor/sigs.k8s.io/controller-tools/pkg/webhook/parser.go
  vendor/sigs.k8s.io/controller-tools/pkg/webhook/zz_generated.markerhelp.go
Labels: kind/cleanup, kind/dependencies

#396 internalstorage: fix notin and != operator in JSONBuilder
  pkg/storage/internalstorage/builder.go
  pkg/storage/internalstorage/util_test.go
Labels: kind/bug, cherry-pick/0.5.x

#402 update image and chart version
  charts/clusterpedia/Chart.yaml
  charts/clusterpedia/values.yaml
  deploy/clusterpedia_apiserver_deployment.yaml
  deploy/clusterpedia_clustersynchro_manager_deployment.yaml
  deploy/clusterpedia_controller_manager_deployment.yaml
Labels: kind/cleanup, cherry-pick/0.5.x

#403 Bump k8s.io/kubernetes from 1.25.1 to 1.25.2
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go
  vendor/modules.txt
Labels: kind/cleanup, kind/dependencies

#406 update charts index.yaml
  charts/index.yaml
Labels: kind/cleanup
