Repository clusterpedia-io/clusterpedia, pull requests merged in 2022-12, with the labels that each got.

#465 make synchromanager worker configurable
  .gitignore
  cmd/clustersynchro-manager/app/config/config.go
  cmd/clustersynchro-manager/app/options/options.go
  cmd/clustersynchro-manager/app/synchro.go
Labels: kind/feature, lgtm, size/S

#470 fix image version when multiple tags exist on HEAD
  .github/workflows/push-images.yml
  Makefile
Labels: kind/bug, size/S

#471 Update response message for requesting a non-existing cluster
  pkg/kubeapiserver/resource_handler.go
Labels: lgtm, size/XS

#473 update deploy image tag to v0.6.0
  deploy/clusterpedia_apiserver_deployment.yaml
  deploy/clusterpedia_clustersynchro_manager_deployment.yaml
  deploy/clusterpedia_controller_manager_deployment.yaml
Labels: kind/cleanup, size/XS

#475 fix shutdown cluster synchro
  pkg/synchromanager/clustersynchro/cluster_monitor.go
  pkg/synchromanager/clustersynchro/cluster_synchro.go
Labels: kind/bug, size/M

#477 [release/0.6] fix shutdown cluster synchro
  pkg/synchromanager/clustersynchro/cluster_monitor.go
  pkg/synchromanager/clustersynchro/cluster_synchro.go
Labels: size/M
