Repository clusterpedia-io/clusterpedia, pull requests merged in 2022-10, with the labels that each got.

#407 return all resources if groups=* is given
  pkg/storage/internalstorage/collectionresource_storage.go
Labels: lgtm

#413 Add Logger Config To Charts
  charts/clusterpedia/Chart.yaml
  charts/clusterpedia/templates/internalstorage-configmap.yaml
  charts/clusterpedia/values.yaml
  pkg/storage/internalstorage/register.go
Labels: lgtm

#415 Add cancel-lgtm action
  .github/workflows/pr-labeling.yml
Labels: kind/feature, lgtm

#419 Fix PR labeling
  .github/workflows/pr-labeling.yml
Labels: kind/bug, size/XS

#420 Bump gorm.io/gorm from 1.23.10 to 1.24.0
  go.mod
  go.sum
  pkg/storage/internalstorage/resource_storage_test.go
  pkg/storage/internalstorage/util.go
  pkg/storage/internalstorage/util_test.go
  vendor/gorm.io/gorm/chainable_api.go
  vendor/gorm.io/gorm/clause/limit.go
  vendor/gorm.io/gorm/clause/on_conflict.go
  vendor/gorm.io/gorm/finisher_api.go
  vendor/gorm.io/gorm/gorm.go
  vendor/gorm.io/gorm/prepare_stmt.go
  vendor/gorm.io/gorm/scan.go
  vendor/gorm.io/gorm/schema/relationship.go
  vendor/gorm.io/gorm/schema/schema.go
  vendor/modules.txt
Labels: kind/cleanup, lgtm, kind/dependencies, size/L

#424 add artifact hub badge
  README.md
Labels: kind/cleanup, size/XS

#425 migrate charts to clusterpedia-helm repo
  .github/workflows/lint-chart.yaml
  charts/clusterpedia/README.md
  deploy/cluster.clusterpedia.io_clustersyncresources.yaml
  deploy/cluster.clusterpedia.io_pediaclusters.yaml
  deploy/crds/cluster.clusterpedia.io_clustersyncresources.yaml
  deploy/crds/cluster.clusterpedia.io_pediaclusters.yaml
  deploy/crds/policy.clusterpedia.io_clusterimportpolicies.yaml
  deploy/crds/policy.clusterpedia.io_pediaclusterlifecycles.yaml
  deploy/policy.clusterpedia.io_clusterimportpolicies.yaml
  deploy/policy.clusterpedia.io_pediaclusterlifecycles.yaml
  hack/update-crds.sh
  hack/verify-crds.sh
  test/helper.sh
Labels: kind/cleanup, size/XL

#431 check cluster whether exist
  pkg/kubeapiserver/resource_handler.go
Labels: kind/bug, lgtm, size/M
