Repository clusterpedia-io/clusterpedia, pull requests merged in 2023-11, with the labels that each got.

#582 check length of vds
  pkg/kubeapiserver/discovery/group.go
Labels: kind/bug, size/XS

#583 kubeapiserver/discovery: use sets.Set[T] instead of `map[T]struct{}` and optimze other code
  pkg/kubeapiserver/discovery/discovery.go
  pkg/kubeapiserver/discovery/group.go
  pkg/kubeapiserver/discovery/version.go
  pkg/kubeapiserver/restmanager.go
Labels: kind/cleanup, size/M

#584 cmd/apiserver: clean up commented out code
  cmd/apiserver/app/options/options.go
Labels: kind/cleanup, size/XS

#588 support openapi v2 for compatibility lower kubernete versions
  cmd/apiserver/app/options/options.go
Labels: size/XS

#592 resource synch process for delete event
  pkg/synchromanager/clustersynchro/resource_synchro.go
Labels: kind/bug, size/S

#598 make DB bad connection error message more specific
  pkg/storage/internalstorage/errors.go
Labels: kind/feature, size/XS

#602 chore: updated .gitignore to ignore the certificates related files during development and testing
  .gitignore
Labels: size/XS

#597 feat: added new parameters for parameterized query
  pkg/storage/internalstorage/features.go
  pkg/storage/internalstorage/storage_test.go
  pkg/storage/internalstorage/util.go
  pkg/storage/internalstorage/util_test.go
  vendor/github.com/stretchr/testify/require/doc.go
  vendor/github.com/stretchr/testify/require/forward_requirements.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require.go.tmpl
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/github.com/stretchr/testify/require/require_forward.go.tmpl
  vendor/github.com/stretchr/testify/require/requirements.go
  vendor/modules.txt
Labels: kind/bug, kind/feature, size/XXL

#603 [release/0.7] feat: added new parameters for parameterized query
  pkg/storage/internalstorage/storage_test.go
  pkg/storage/internalstorage/util.go
  pkg/storage/internalstorage/util_test.go
  vendor/github.com/stretchr/testify/require/doc.go
  vendor/github.com/stretchr/testify/require/forward_requirements.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require.go.tmpl
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/github.com/stretchr/testify/require/require_forward.go.tmpl
  vendor/github.com/stretchr/testify/require/requirements.go
  vendor/modules.txt
Labels: kind/bug, size/XXL

#591 clustersynchro: handle each of the pages in the resource list stage
  cmd/binding-apiserver/app/binding_apiserver.go
  cmd/clustersynchro-manager/app/config/config.go
  cmd/clustersynchro-manager/app/options/options.go
  cmd/clustersynchro-manager/app/synchro.go
  hack/verify-vendor.sh
  pkg/synchromanager/clustersynchro/cluster_synchro.go
  pkg/synchromanager/clustersynchro/informer/named_controller.go
  pkg/synchromanager/clustersynchro/informer/pager/.pager.go.copy
  pkg/synchromanager/clustersynchro/informer/pager/pager.go
  pkg/synchromanager/clustersynchro/informer/pager/result_stream.go
  pkg/synchromanager/clustersynchro/informer/reflector.go
  pkg/synchromanager/clustersynchro/informer/resourceversion_informer.go
  pkg/synchromanager/clustersynchro/resource_synchro.go
  pkg/synchromanager/clustersynchro_manager.go
  pkg/synchromanager/features/features.go
Labels: kind/feature, size/XL

#608 chore: added more certificate and test use sqlite db related ignore for `.gitignore`
  .gitignore
Labels: kind/cleanup, size/S

#607 fix: direct `[]byte` write when updating resources
  pkg/storage/internalstorage/resource_storage.go
  pkg/storage/internalstorage/resource_storage_test.go
  pkg/storage/internalstorage/storage_test.go
  pkg/storage/internalstorage/util_test.go
Labels: kind/bug, size/L
