Repository clusterpedia-io/clusterpedia, pull requests merged in 2023-02, with the labels that each got.

#486 Optimize the document for readability
  MAINTAINERS.md
  README.md
Labels: kind/documentation, size/S

#485 Bump kwokctl to v0.1.0
  test/helper.sh
Labels: kind/feature, size/XS

#491 fix spell: stoped
  pkg/discovery/dynamic_discovery.go
  pkg/synchromanager/clustersynchro/resource_synchro.go
Labels: lgtm, size/S

#494 fix: Wrong timeout configuration value
  pkg/kubeapiserver/apiserver.go
Labels: kind/bug, lgtm, size/XS, cherry-pick/0.6.x

#493 resource synchro: fix set runnable for storage
  pkg/synchromanager/clustersynchro/resource_synchro.go
Labels: kind/bug, size/M, cherry-pick/0.6.x

#495 optimize calculate paging count
  pkg/storage/internalstorage/collectionresource_storage.go
  pkg/storage/internalstorage/resource_storage.go
  pkg/storage/internalstorage/resource_storage_test.go
  pkg/storage/internalstorage/types.go
Labels: kind/feature, size/M, cherry-pick/0.6.x

#499 [release/0.6] optimize calculate paging count
  pkg/storage/internalstorage/collectionresource_storage.go
  pkg/storage/internalstorage/resource_storage.go
  pkg/storage/internalstorage/resource_storage_test.go
  pkg/storage/internalstorage/types.go
Labels: kind/feature, size/M

#500 [release/0.6] fix: Wrong timeout configuration value
  pkg/kubeapiserver/apiserver.go
Labels: kind/bug, lgtm, size/XS

#502 [release/0.6] resource synchro: fix set runnable for storage
  pkg/synchromanager/clustersynchro/resource_synchro.go
Labels: kind/bug, lgtm, size/M

#504 fix: owner spell
  pkg/controller/pediaclusterlifecycle/pediaclusterlifecycle_controller.go
Labels: size/XS

#503 fix cross compile
  hack/builder.sh
Labels: kind/bug, size/XS

#505 cluster synchro: add warning log for shutdown blocking
  pkg/synchromanager/clustersynchro/cluster_monitor.go
  pkg/synchromanager/clustersynchro/cluster_synchro.go
  pkg/synchromanager/clustersynchro/resource_synchro.go
Labels: kind/cleanup, size/M
