Repository clusterpedia-io/clusterpedia, pull requests merged in 2023-07, with the labels that each got.

#534 deploy: update image tag to v0.7.0
  deploy/clusterpedia_apiserver_deployment.yaml
  deploy/clusterpedia_clustersynchro_manager_deployment.yaml
  deploy/clusterpedia_controller_manager_deployment.yaml
Labels: size/XS

#526 add memory filter lable select
  pkg/storage/memorystorage/watchcache/watch_cache.go
  pkg/storage/memorystorage/watchcache/watch_cache_test.go
Labels: kind/feature, lgtm, size/L

#540 ci: bump golang and golangci-lint
  .github/workflows/ci.yml
  Makefile
Labels: size/S

#541 :seedling: add unit tests for events.go
  pkg/synchromanager/clustersynchro/queue/event_test.go
Labels: kind/feature, size/L

#550 :seedling: added tests for controller package
  pkg/controller/result_test.go
Labels: kind/feature, size/M

#542 update ROADMAP
  ROADMAP.md
Labels: kind/cleanup, size/M
