Repository clusterpedia-io/clusterpedia, pull requests merged in 2023-10, with the labels that each got.

#575 ci: remove the old singular releases
  test/environments/multiple.env.sh
Labels: size/XS

#576 Bump control plane to 1.28 for e2e
  test/environments/default.env.sh
  test/environments/multiple.env.sh
Labels: kind/cleanup, size/S

#581 :seedling: migrate golang from 1.20 to 1.21.3
  .github/workflows/ci.yml
  builder.dockerfile
Labels: kind/dependencies, size/S
