Repository clusterpedia-io/clusterpedia, pull requests merged in 2023-08, with the labels that each got.

#553 kube-state-metrics: support for exposing single cluster metrics
  go.mod
  go.sum
  pkg/kube_state_metrics/landing_page/landing_page.css
  pkg/kube_state_metrics/landing_page/landing_page.html
  pkg/kube_state_metrics/metrics_handler.go
  pkg/kube_state_metrics/server.go
  pkg/metrics/server.go
  vendor/github.com/gorilla/mux/AUTHORS
  vendor/github.com/gorilla/mux/LICENSE
  vendor/github.com/gorilla/mux/README.md
  vendor/github.com/gorilla/mux/doc.go
  vendor/github.com/gorilla/mux/middleware.go
  vendor/github.com/gorilla/mux/mux.go
  vendor/github.com/gorilla/mux/regexp.go
  vendor/github.com/gorilla/mux/route.go
  vendor/github.com/gorilla/mux/test_helpers.go
  vendor/modules.txt
Labels: size/L

#551 :seedling: upgrade to Kustomize configuration
  kustomize/apiserver/clusterpedia_apiserver_apiservice.yaml
  kustomize/apiserver/clusterpedia_apiserver_deployment.yaml
  kustomize/apiserver/kustomization.yaml
  kustomize/binding-apiserver/clusterpedia_binding_apiserver_apiservice.yaml
  kustomize/binding-apiserver/clusterpedia_binding_apiserver_deployment.yaml
  kustomize/binding-apiserver/clusterpedia_binding_apiserver_rbac.yaml
  kustomize/binding-apiserver/kustomization.yaml
  kustomize/clustersynchro-manager/clusterpedia_clustersynchro_manager_deployment.yaml
  kustomize/clustersynchro-manager/kustomization.yaml
  kustomize/controller-manager/clusterpedia_controller_manager_deployment.yaml
  kustomize/controller-manager/kustomization.yaml
  kustomize/crds/cluster.clusterpedia.io_clustersyncresources.yaml
  kustomize/crds/cluster.clusterpedia.io_pediaclusters.yaml
  kustomize/crds/kustomization.yaml
  kustomize/crds/policy.clusterpedia.io_clusterimportpolicies.yaml
  kustomize/crds/policy.clusterpedia.io_pediaclusterlifecycles.yaml
  kustomize/internalstorage/mysql/clusterpedia_internalstorage_configmap.yaml
  kustomize/internalstorage/mysql/clusterpedia_internalstorage_deployment.yaml
  kustomize/internalstorage/mysql/clusterpedia_internalstorage_secret.yaml
  kustomize/internalstorage/mysql/kustomization.yaml
  kustomize/internalstorage/postgres/clusterpedia_internalstorage_configmap.yaml
  kustomize/internalstorage/postgres/clusterpedia_internalstorage_deployment.yaml
  kustomize/internalstorage/postgres/clusterpedia_internalstorage_secret.yaml
  kustomize/internalstorage/postgres/kustomization.yaml
  kustomize/kustomization.yaml
Labels: kind/feature, size/XXL

#556 kustomize: add namespace.yaml
  kustomize/internalstorage/mysql/clusterpedia_internalstorage_configmap.yaml
  kustomize/internalstorage/postgres/clusterpedia_internalstorage_configmap.yaml
  kustomize/kustomization.yaml
  kustomize/namespace.yaml
Labels: size/S

#560 kustomize for e2e tests
  kustomize/apiserver/clusterpedia_apiserver_apiservice.yaml
  kustomize/internalstorage/postgres/clusterpedia_internalstorage_secret.yaml
  test/helper.sh
  test/kustomize/kustomization.yaml
  test/kustomize/pvc.patch.yaml
  test/test.sh
Labels: kind/feature, lgtm, size/M

#561 update /deploy dir and move crds to kustomize/crds
  deploy/binding-apiserver/clusterpedia_binding_apiserver_apiservice.yaml
  deploy/binding-apiserver/clusterpedia_binding_apiserver_deployment.yaml
  deploy/binding-apiserver/clusterpedia_binding_apiserver_rbac.yaml
  deploy/cluster.clusterpedia.io_clustersyncresources.yaml
  deploy/cluster.clusterpedia.io_pediaclusters.yaml
  deploy/crds/cluster.clusterpedia.io_clustersyncresources.yaml
  deploy/crds/cluster.clusterpedia.io_pediaclusters.yaml
  deploy/crds/policy.clusterpedia.io_clusterimportpolicies.yaml
  deploy/crds/policy.clusterpedia.io_pediaclusterlifecycles.yaml
  deploy/policy.clusterpedia.io_clusterimportpolicies.yaml
  deploy/policy.clusterpedia.io_pediaclusterlifecycles.yaml
  hack/update-crds.sh
  hack/verify-crds.sh
  kustomize/clusterimportpolicy/cluster_api.yaml
  kustomize/clusterimportpolicy/karmada.yaml
  kustomize/clusterimportpolicy/kubevela.yaml
  kustomize/clusterimportpolicy/vcluster.yaml
Labels: kind/cleanup, size/XL

#563 :fire: remove helm charts
  charts/OWNERS
  charts/artifacthub-repo.yml
  charts/clusterpedia/.helmignore
  charts/clusterpedia/Chart.lock
  charts/clusterpedia/Chart.yaml
  charts/clusterpedia/README.md
  charts/clusterpedia/_crds/cluster.clusterpedia.io_clustersyncresources.yaml
  charts/clusterpedia/_crds/cluster.clusterpedia.io_pediaclusters.yaml
  charts/clusterpedia/_crds/policy.clusterpedia.io_clusterimportpolicies.yaml
  charts/clusterpedia/_crds/policy.clusterpedia.io_pediaclusterlifecycles.yaml
  charts/clusterpedia/templates/NOTES.txt
  charts/clusterpedia/templates/_helpers.tpl
  charts/clusterpedia/templates/apiserver-apiservice.yaml
  charts/clusterpedia/templates/apiserver-deployment.yaml
  charts/clusterpedia/templates/apiserver-service.yaml
  charts/clusterpedia/templates/apiserver-serviceaccount.yaml
  charts/clusterpedia/templates/clusterrole.yaml
  charts/clusterpedia/templates/clusterrolebinding.yaml
  charts/clusterpedia/templates/clustersynchro-manager-deployment.yaml
  charts/clusterpedia/templates/clustersynchro-manager-serviceaccount.yaml
  charts/clusterpedia/templates/controller-manager-deployment.yaml
  charts/clusterpedia/templates/controller-manager-serviceaccount.yaml
  charts/clusterpedia/templates/customresourcedefinitions.yaml
  charts/clusterpedia/templates/internalstorage-configmap.yaml
  charts/clusterpedia/templates/internalstorage-local-pv-check-job.yaml
  charts/clusterpedia/templates/internalstorage-local-pv.yaml
  charts/clusterpedia/templates/internalstorage-secret.yaml
  charts/clusterpedia/values.yaml
  charts/index.yaml
Labels: size/XXL

#566 #546 add kube state metrics namespace command
  pkg/kube_state_metrics/metrics_store.go
  pkg/kube_state_metrics/options.go
Labels: kind/feature, size/M
