Repository clusterpedia-io/clusterpedia, pull requests merged in 2023-01, with the labels that each got.

#479 add retry for mysql read-only error
  pkg/storage/internalstorage/config.go
  pkg/storage/internalstorage/errors.go
  pkg/storage/internalstorage/register.go
Labels: kind/bug, lgtm, size/M, cherry-pick/0.6.x

#480 Support for configuring database recoverable errors
  pkg/storage/internalstorage/config.go
  pkg/storage/internalstorage/errors.go
  pkg/storage/internalstorage/register.go
Labels: kind/feature, size/M

#482 clustersynchro: fix enable and disable concurrent
  pkg/synchromanager/clustersynchro/resource_negotiator.go
Labels: kind/bug, size/XS, cherry-pick/0.6.x

#483 [release/0.6] clustersynchro: fix enable and disable concurrent
  pkg/synchromanager/clustersynchro/resource_negotiator.go
Labels: kind/bug, size/XS
