Repository clusterpedia-io/clusterpedia, pull requests merged in 2023-12, with the labels that each got.

#612 optimize-comments, convert comment language zh to en
  pkg/kubeapiserver/discovery/discovery.go
  pkg/synchromanager/clustersynchro/queue/event.go
Labels: kind/cleanup, size/S

#604 add OTEL trace for clusterpedia-apiserver
  cmd/apiserver/app/options/options.go
  deploy/clusterpedia_apiserver_deployment.yaml
  kustomize/apiserver/clusterpedia_apiserver_deployment.yaml
  pkg/apiserver/apiserver.go
  pkg/kubeapiserver/apiserver.go
Labels: kind/feature, size/M

#609 add sharding feature for ClusterSynchroManager
  cmd/binding-apiserver/app/binding_apiserver.go
  cmd/clustersynchro-manager/app/config/config.go
  cmd/clustersynchro-manager/app/options/options.go
  cmd/clustersynchro-manager/app/synchro.go
  kustomize/crds/cluster.clusterpedia.io_pediaclusters.yaml
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/synchromanager/clustersynchro_manager.go
  staging/src/github.com/clusterpedia-io/api/cluster/v1alpha2/types.go
  staging/src/github.com/clusterpedia-io/api/cluster/v1alpha2/zz_generated.deepcopy.go
Labels: size/M

#619 bump golangci-lint to v1.54
  .github/workflows/ci.yml
  Makefile
Labels: size/XS

#615 add featureGate IgnoreLeaseSync to stop sync leases.coordination.k8s.io
  pkg/synchromanager/clustersynchro/resource_negotiator.go
  pkg/synchromanager/features/features.go
Labels: kind/feature, size/S

#621 [release/0.7] add featureGate IgnoreLeaseSync to stop sync leases.coordination.k8s.io
  pkg/synchromanager/clustersynchro/resource_negotiator.go
  pkg/synchromanager/features/features.go
Labels: size/S

#622 featureGate: IgnoreLeaseSync => IgnoreSyncLease
  pkg/synchromanager/clustersynchro/resource_negotiator.go
  pkg/synchromanager/features/features.go
Labels: size/XS

#623 [release/0.7] featureGate: IgnoreLeaseSync => IgnoreSyncLease
  pkg/synchromanager/clustersynchro/resource_negotiator.go
  pkg/synchromanager/features/features.go
Labels: size/XS

#624 fix: CleanClusterResource add WithContext
  pkg/storage/internalstorage/storage.go
Labels: size/XS

#625 add ConvertDeletedObject method for ResourceStorage
  pkg/storage/internalstorage/resource_storage.go
  pkg/storage/memorystorage/memory_resource_storage.go
  pkg/storage/storage.go
  pkg/synchromanager/clustersynchro/resource_synchro.go
Labels: kind/feature, size/M

#627 set the default value of the feature gate APIServerTracing to false
  cmd/apiserver/app/apiserver.go
  kustomize/apiserver/clusterpedia_apiserver_deployment.yaml
Labels: kind/feature, size/S

#629 update the created_at field when updating resource
  pkg/storage/internalstorage/resource_storage.go
Labels: kind/bug, size/XS

#631 Revert "set the default value of the feature gate APIServerTracing to false" #627
  cmd/apiserver/app/apiserver.go
  kustomize/apiserver/clusterpedia_apiserver_deployment.yaml
Labels: size/S

#632 Fix incorrect image link for CNCF cloud gophers
  README.md
Labels: kind/documentation, size/XS

#628 add logging with stream handling enabled
  pkg/synchromanager/clustersynchro/informer/reflector.go
Labels: kind/feature, size/XS
