Repository clusterpedia-io/clusterpedia, pull requests merged in 2024-11, with the labels that each got.

#704 bump kubernetes to v1.31.2
  go.mod
  go.sum
  vendor/k8s.io/api/resource/v1alpha3/generated.pb.go
  vendor/k8s.io/api/resource/v1alpha3/generated.proto
  vendor/k8s.io/api/resource/v1alpha3/types.go
  vendor/k8s.io/api/resource/v1alpha3/types_swagger_doc_generated.go
  vendor/k8s.io/apiserver/pkg/server/options/tracing.go
  vendor/k8s.io/apiserver/pkg/server/storage/resource_encoding_config.go
  vendor/k8s.io/apiserver/pkg/server/storage/storage_factory.go
  vendor/k8s.io/apiserver/pkg/util/version/version.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/modules.txt
Labels: kind/dependencies, size/M

#705 test: check the clusterpedia apiserver before test cases
  test/environments/multiple.env.sh
  test/environments/single.env.sh
  test/helper.sh
Labels: size/S, kind/test

#706 memorystorage: fix deleting cluster info when cleaning a resource
  pkg/storage/memorystorage/memory_storage.go
Labels: kind/bug, size/XS

#707 add kubeVela and vCluster in Readme
  README.md
Labels: kind/documentation, size/XS

#708 add memory storage layer v2
  .golangci.yml
  pkg/storage/memorystorage/v2/README.md
  pkg/storage/memorystorage/v2/cache_watcher.go
  pkg/storage/memorystorage/v2/register.go
  pkg/storage/memorystorage/v2/resource_storage.go
  pkg/storage/memorystorage/v2/storage.go
  pkg/storage/memorystorage/v2/versioner.go
  pkg/storage/memorystorage/v2/watch_cache_interval.go
Labels: kind/feature, size/XXL
