Repository clusterpedia-io/clusterpedia, pull requests merged in 2024-12, with the labels that each got.

#711 internalstorage: add gorm database metrics
  pkg/storage/internalstorage/metrics.go
  pkg/storage/internalstorage/register.go
Labels: kind/feature, size/L

#712 internalstorage: add metrics config
  pkg/storage/internalstorage/config.go
  pkg/storage/internalstorage/metrics.go
  pkg/storage/internalstorage/register.go
Labels: kind/feature, size/M

#713 internalstorage: change the prefix of the db stats metrics
  pkg/storage/internalstorage/metrics.go
Labels: kind/feature, size/S

#714 internalstorage: add trace
  go.mod
  pkg/storage/internalstorage/collectionresource_storage.go
  pkg/storage/internalstorage/register.go
  pkg/storage/internalstorage/resource_storage.go
  pkg/storage/internalstorage/tracing.go
Labels: kind/feature, size/L

#715 support pod subresources
  go.mod
  go.sum
  pkg/apiserver/registry/clusterpedia/resources/rest.go
  pkg/kubeapiserver/apiserver.go
  pkg/kubeapiserver/clusterresource_controller.go
  pkg/kubeapiserver/resource_handler.go
  pkg/kubeapiserver/resourcerest/pod/subresource.go
  pkg/kubeapiserver/resourcerest/storage.go
  pkg/kubeapiserver/restmanager.go
  vendor/github.com/mxk/go-flowrate/LICENSE
  vendor/github.com/mxk/go-flowrate/flowrate/flowrate.go
  vendor/github.com/mxk/go-flowrate/flowrate/io.go
  vendor/github.com/mxk/go-flowrate/flowrate/util.go
  vendor/golang.org/x/net/html/atom/atom.go
  vendor/golang.org/x/net/html/atom/table.go
  vendor/golang.org/x/net/html/const.go
  vendor/golang.org/x/net/html/doc.go
  vendor/golang.org/x/net/html/doctype.go
  vendor/golang.org/x/net/html/entity.go
  vendor/golang.org/x/net/html/escape.go
  vendor/golang.org/x/net/html/foreign.go
  vendor/golang.org/x/net/html/node.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/html/render.go
  vendor/golang.org/x/net/html/token.go
  vendor/k8s.io/apimachinery/pkg/util/proxy/dial.go
  vendor/k8s.io/apimachinery/pkg/util/proxy/doc.go
  vendor/k8s.io/apimachinery/pkg/util/proxy/transport.go
  vendor/k8s.io/apimachinery/pkg/util/proxy/upgradeaware.go
  vendor/k8s.io/apimachinery/third_party/forked/golang/netutil/addr.go
  vendor/modules.txt
Labels: kind/feature, size/L

#716 apiserver: Adding RemoteProxyREST for pass-through any requests
  pkg/kubeapiserver/apiserver.go
  pkg/kubeapiserver/resource_handler.go
  pkg/kubeapiserver/resourcerest/pod/subresource.go
  pkg/kubeapiserver/resourcerest/proxy/proxy.go
  pkg/kubeapiserver/resourcerest/proxy/subresource.go
Labels: kind/feature, size/L
