Repository clusterpedia-io/clusterpedia, pull requests merged in 2024-01, with the labels that each got.

#637 0.8.0: update image version of deploy manifests
  deploy/clusterpedia_apiserver_deployment.yaml
  deploy/clusterpedia_clustersynchro_manager_deployment.yaml
  deploy/clusterpedia_controller_manager_deployment.yaml
  kustomize/apiserver/clusterpedia_apiserver_deployment.yaml
  kustomize/clustersynchro-manager/clusterpedia_clustersynchro_manager_deployment.yaml
  kustomize/controller-manager/clusterpedia_controller_manager_deployment.yaml
Labels: kind/cleanup, size/S

#641 Change the storage plugin name to sample-storage
  hack/builder.sh
Labels: size/XS

#646 feat: add pprof router
  go.mod
  go.sum
  pkg/metrics/server.go
  pkg/pprof/handler.go
  vendor/modules.txt
Labels: size/S

#638 fix otel trace handler WithTracing, use another func
  pkg/kubeapiserver/apiserver.go
Labels: kind/bug, size/XS
