Repository clusterpedia-io/clusterpedia, pull requests merged in 2024-06, with the labels that each got.

#670 update hack/.import-aliases
  hack/.import-aliases
Labels: kind/cleanup, size/M

#671 golangci-lint: remove deprecated linters
  .golangci.yml
Labels: kind/cleanup, size/XS

#672 install storagemigration group to LegacyResourceScheme
  pkg/scheme/import_known_versions.go
  vendor/k8s.io/kubernetes/pkg/apis/storagemigration/install/install.go
  vendor/k8s.io/kubernetes/pkg/apis/storagemigration/v1alpha1/doc.go
  vendor/k8s.io/kubernetes/pkg/apis/storagemigration/v1alpha1/register.go
  vendor/k8s.io/kubernetes/pkg/apis/storagemigration/v1alpha1/zz_generated.conversion.go
  vendor/k8s.io/kubernetes/pkg/apis/storagemigration/v1alpha1/zz_generated.defaults.go
  vendor/modules.txt
Labels: size/XS

#674 apiserver: remove admission middleware
  cmd/apiserver/app/options/options.go
Labels: kind/feature, size/S

#675 apiserver: unlock the RemainingItemCount feature gate
  cmd/apiserver/app/apiserver.go
Labels: kind/bug, size/XS

#676 e2e: add test for several control plane versions
  test/environments/multiple.env.sh
  test/environments/single.env.sh
  test/test.sh
Labels: size/M, kind/test

#596 Use actions to install kwokctl
  .github/workflows/ci.yml
  test/helper.sh
Labels: kind/cleanup, size/S

#682 move discovery, scheme and informer to pkg/runtime
  cmd/controller-manager/app/controllermanager.go
  hack/verify-forked-code.sh
  pkg/controller/dependentresource_manager.go
  pkg/kube_state_metrics/metrics_store.go
  pkg/kubeapiserver/restmanager.go
  pkg/runtime/discovery/controller/apiservice.go
  pkg/runtime/discovery/controller/crd.go
  pkg/runtime/discovery/discovery_cache.go
  pkg/runtime/discovery/dynamic_discovery.go
  pkg/runtime/discovery/server_version.go
  pkg/runtime/informer/cache/.reflector.go
  pkg/runtime/informer/event_handler.go
  pkg/runtime/informer/informer.go
  pkg/runtime/informer/listwatch.go
  pkg/runtime/informer/named_controller.go
  pkg/runtime/informer/pager/.pager.go.copy
  pkg/runtime/informer/pager/pager.go
  pkg/runtime/informer/pager/result_stream.go
  pkg/runtime/informer/queue.go
  pkg/runtime/informer/reflector.go
  pkg/runtime/informer/resourceversion_informer.go
  pkg/runtime/informer/resourceversion_storage.go
  pkg/runtime/scheme/import_known_versions.go
  pkg/runtime/scheme/scheme.go
  pkg/runtime/scheme/unstructured/scheme.go
  pkg/storage/internalstorage/collectionresource.go
  pkg/storage/memorystorage/watchcache/watch_cache.go
  pkg/storageconfig/storageconfig_factory.go
  pkg/synchromanager/clustersynchro/cluster_synchro.go
  pkg/synchromanager/clustersynchro/resource_negotiator.go
  pkg/synchromanager/clustersynchro/resource_synchro.go
Labels: kind/cleanup, size/M

#678 add pkg/runtime/resourceconfig.ResourceConfig
  pkg/apiserver/registry/clusterpedia/collectionresources/rest.go
  pkg/kube_state_metrics/metrics_store.go
  pkg/kubeapiserver/restmanager.go
  pkg/runtime/resourceconfig/factory/resourceconfig_factory.go
  pkg/runtime/resourceconfig/resource_config.go
  pkg/storage/internalstorage/resource_storage.go
  pkg/storage/internalstorage/resource_storage_test.go
  pkg/storage/internalstorage/storage.go
  pkg/storage/memorystorage/memory_resource_storage.go
  pkg/storage/memorystorage/memory_storage.go
  pkg/storage/storage.go
  pkg/synchromanager/clustersynchro/cluster_synchro.go
  pkg/synchromanager/clustersynchro/resource_negotiator.go
  pkg/synchromanager/clustersynchro/resource_synchro.go
Labels: kind/feature, size/L
