Repository clusterpedia-io/clusterpedia, pull requests merged in 2024-08, with the labels that each got.

#689 bump golang from 1.22.4 to 1.22.6
  builder.dockerfile
Labels: kind/dependencies, size/S

#690 dependabot: ignore minor version for golang and alpine images
  .github/dependabot.yml
Labels: kind/cleanup, size/XS

#694 metrics: use legacyregister instead of new registry
  pkg/kube_state_metrics/server.go
  pkg/metrics/metrics.go
  pkg/metrics/server.go
Labels: kind/feature, size/S

#693 kustomize: remove traces config
  deploy/clusterpedia_apiserver_deployment.yaml
  kustomize/apiserver/clusterpedia_apiserver_deployment.yaml
Labels: kind/bug, size/M

#695 metrics: register clusterpedia and kubernetes build info
  cmd/apiserver/app/apiserver.go
  cmd/clustersynchro-manager/app/config/config.go
  cmd/clustersynchro-manager/app/options/options.go
  cmd/clustersynchro-manager/app/synchro.go
  pkg/kube_state_metrics/options.go
  pkg/kube_state_metrics/server.go
  pkg/metrics/metrics.go
  pkg/metrics/server/logger.go
  pkg/metrics/server/options.go
  pkg/metrics/server/server.go
  pkg/metrics/version.go
  vendor/github.com/prometheus/client_golang/prometheus/collectors/version/version.go
  vendor/k8s.io/component-base/metrics/prometheus/version/metrics.go
  vendor/modules.txt
Labels: kind/bug, kind/feature, size/M

#696 metrics: add component-base/metrics.Options
  cmd/apiserver/app/options/options.go
  pkg/metrics/server/options.go
Labels: kind/feature, size/S
