Repository clusterpedia-io/clusterpedia, pull requests merged in 2025-02, with the labels that each got.

#726 ci: bump upload artifact to v4
  .github/workflows/ci.yml
Labels: kind/cleanup, size/XS

#724 Support shutting down storage factory
  cmd/apiserver/app/apiserver.go
  cmd/binding-apiserver/app/binding_apiserver.go
  cmd/clustersynchro-manager/app/synchro.go
  pkg/storage/internalstorage/storage.go
  pkg/storage/memorystorage/memory_storage.go
  pkg/storage/memorystorage/v2/storage.go
  pkg/storage/storage.go
Labels: kind/feature, size/M

#723 apiserver: add enable subresource options
  cmd/apiserver/app/options/options.go
  pkg/apiserver/apiserver.go
  pkg/kubeapiserver/apiserver.go
  pkg/kubeapiserver/options.go
Labels: kind/feature, size/L

#727 apiserver: set proxy auth info via request header
  pkg/kubeapiserver/apiserver.go
  pkg/kubeapiserver/clusterresource_controller.go
  pkg/kubeapiserver/options.go
  pkg/kubeapiserver/resourcerest/proxy/proxy.go
  pkg/kubeapiserver/resourcerest/proxy/proxy_connector.go
  pkg/synchromanager/clustersynchro_manager.go
  pkg/utils/rest.go
Labels: kind/feature, size/L
