Repository clusterpedia-io/clusterpedia, pull requests merged in 2025-03, with the labels that each got.

#741 apiserver: forward request with prefix path or header
  pkg/kubeapiserver/apiserver.go
  pkg/kubeapiserver/resource_handler.go
  pkg/kubeapiserver/resourcerest/proxy/proxy.go
Labels: kind/feature, size/M

#749 fix shutdown the storage factory
  cmd/clustersynchro-manager/app/synchro.go
Labels: kind/bug, size/S

#748 apiserver: forward list request with labelselector
  pkg/kubeapiserver/resource_handler.go
  staging/src/github.com/clusterpedia-io/api/clusterpedia/types.go
Labels: kind/feature, size/M

#747 support referencing cluster authentication info from secrets
  cmd/apiserver/app/options/options.go
  cmd/binding-apiserver/app/binding_apiserver.go
  cmd/clustersynchro-manager/app/config/config.go
  cmd/clustersynchro-manager/app/options/options.go
  cmd/clustersynchro-manager/app/synchro.go
  kustomize/crds/cluster.clusterpedia.io_pediaclusters.yaml
  pkg/apiserver/apiserver.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/kubeapiserver/apiserver.go
  pkg/kubeapiserver/resourcerest/proxy/proxy.go
  pkg/kubeapiserver/resourcerest/proxy/proxy_connector.go
  pkg/synchromanager/clustersynchro_manager.go
  pkg/utils/rest.go
  staging/src/github.com/clusterpedia-io/api/cluster/v1alpha2/types.go
Labels: kind/feature, size/L

#752 apiserver: add feature gate AllowProxyRequestToClusters
  pkg/kubeapiserver/apiserver.go
  pkg/kubeapiserver/features.go
  pkg/kubeapiserver/options.go
  pkg/kubeapiserver/resource_handler.go
Labels: kind/feature, size/M

#753 add feature gate ClusterAuthenticationFromSecret
  pkg/kubeapiserver/apiserver.go
  pkg/kubeapiserver/features.go
  pkg/synchromanager/clustersynchro_manager.go
  pkg/synchromanager/features/features.go
  pkg/utils/rest.go
Labels: size/M

#757 bump github.com/stretchr/testify from 1.9.0 to 1.10.0
  go.mod
  go.sum
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/yaml/yaml_custom.go
  vendor/github.com/stretchr/testify/assert/yaml/yaml_default.go
  vendor/github.com/stretchr/testify/assert/yaml/yaml_fail.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require.go.tmpl
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/github.com/stretchr/testify/require/requirements.go
  vendor/modules.txt
Labels: size/XS

#768 bump github.com/DATA-DOG/go-sqlmock to v1.5.2
  go.mod
  go.sum
  vendor/github.com/DATA-DOG/go-sqlmock/.travis.yml
  vendor/github.com/DATA-DOG/go-sqlmock/README.md
  vendor/github.com/DATA-DOG/go-sqlmock/expectations.go
  vendor/github.com/DATA-DOG/go-sqlmock/expectations_before_go18.go
  vendor/github.com/DATA-DOG/go-sqlmock/expectations_go18.go
  vendor/github.com/DATA-DOG/go-sqlmock/rows.go
  vendor/modules.txt
Labels: size/XS

#771 kubeapiserver: allow using the storage version in request handling
  pkg/kubeapiserver/apiserver.go
  pkg/kubeapiserver/features/features.go
  pkg/kubeapiserver/options.go
  pkg/kubeapiserver/resource_handler.go
  pkg/kubeapiserver/resourcerest/storage.go
  pkg/kubeapiserver/restmanager.go
  pkg/utils/request/mediatype.go
Labels: kind/feature, size/L
