Repository clusterpedia-io/clusterpedia, pull requests merged in 2025-06, with the labels that each got.

#790 kubeapiserver: fix typo
  pkg/kubeapiserver/restmanager.go
Labels: kind/cleanup, size/XS

#791 clustersynchro: add initial list phase
  kustomize/crds/cluster.clusterpedia.io_pediaclusters.yaml
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/synchromanager/clustersynchro/default_resource_synchro.go
  staging/src/github.com/clusterpedia-io/api/cluster/v1alpha2/types.go
Labels: kind/feature, size/M

#792 use sync/atomic instead of go.uber.org/atomic
  go.mod
  go.sum
  pkg/controller/dependentresource_manager.go
  pkg/synchromanager/clustersynchro/default_resource_synchro.go
  vendor/go.uber.org/atomic/.codecov.yml
  vendor/go.uber.org/atomic/.gitignore
  vendor/go.uber.org/atomic/CHANGELOG.md
  vendor/go.uber.org/atomic/LICENSE.txt
  vendor/go.uber.org/atomic/Makefile
  vendor/go.uber.org/atomic/README.md
  vendor/go.uber.org/atomic/bool.go
  vendor/go.uber.org/atomic/bool_ext.go
  vendor/go.uber.org/atomic/doc.go
  vendor/go.uber.org/atomic/duration.go
  vendor/go.uber.org/atomic/duration_ext.go
  vendor/go.uber.org/atomic/error.go
  vendor/go.uber.org/atomic/error_ext.go
  vendor/go.uber.org/atomic/float32.go
  vendor/go.uber.org/atomic/float32_ext.go
  vendor/go.uber.org/atomic/float64.go
  vendor/go.uber.org/atomic/float64_ext.go
  vendor/go.uber.org/atomic/gen.go
  vendor/go.uber.org/atomic/int32.go
  vendor/go.uber.org/atomic/int64.go
  vendor/go.uber.org/atomic/nocmp.go
  vendor/go.uber.org/atomic/pointer_go118.go
  vendor/go.uber.org/atomic/pointer_go118_pre119.go
  vendor/go.uber.org/atomic/pointer_go119.go
  vendor/go.uber.org/atomic/string.go
  vendor/go.uber.org/atomic/string_ext.go
  vendor/go.uber.org/atomic/time.go
  vendor/go.uber.org/atomic/time_ext.go
  vendor/go.uber.org/atomic/uint32.go
  vendor/go.uber.org/atomic/uint64.go
  vendor/go.uber.org/atomic/uintptr.go
  vendor/go.uber.org/atomic/unsafe_pointer.go
  vendor/go.uber.org/atomic/value.go
  vendor/modules.txt
Labels: size/S

#799 fix the initial list phase of resource sync status
  pkg/synchromanager/clustersynchro/cluster_synchro.go
Labels: kind/bug, size/XS

#800 synchro/queue: change HasInitialEvent to HasInitialEvents
  pkg/synchromanager/clustersynchro/default_resource_synchro.go
  pkg/synchromanager/resourcesynchro/queue/pressurequeue.go
  pkg/synchromanager/resourcesynchro/queue/queue.go
Labels: size/XS
